### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by krustchinsky** [CSCE360025/Assignment6#2]
I'm going to arrange things as follows:

* /project
   * /server
   * /client
   * /bin

This allows us to store the sources for each component separately and build them independently or as a whole. There will be a Makefile in each directory containing sources, and the top level Makefile will invoke the others and store the resulting executables in the bin/ directory.

**Comment by T-King** [comment]
I'm fine with that, as long as we can present Sweany with a Bash script that will execute them properly. Executing them with a single Bash script seems to get it stuck at the listen() call, but that's probably what Sweany/Mashiro was referring to if you've read the assignment note.
